// Generated from exptex2.g4 by ANTLR 4.x
package exptex;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.Token;

public interface exptex2Listener extends ParseTreeListener {
	void enterEntity_rm_id(exptex2Parser.Entity_rm_idContext ctx);
	void exitEntity_rm_id(exptex2Parser.Entity_rm_idContext ctx);
	void enterExpr_array(exptex2Parser.Expr_arrayContext ctx);
	void exitExpr_array(exptex2Parser.Expr_arrayContext ctx);
	void enterAtom_set(exptex2Parser.Atom_setContext ctx);
	void exitAtom_set(exptex2Parser.Atom_setContext ctx);
	void enterExpr_prime(exptex2Parser.Expr_primeContext ctx);
	void exitExpr_prime(exptex2Parser.Expr_primeContext ctx);
	void enterAtom_mod(exptex2Parser.Atom_modContext ctx);
	void exitAtom_mod(exptex2Parser.Atom_modContext ctx);
	void enterExpr_binop(exptex2Parser.Expr_binopContext ctx);
	void exitExpr_binop(exptex2Parser.Expr_binopContext ctx);
	void enterAtom_brackets(exptex2Parser.Atom_bracketsContext ctx);
	void exitAtom_brackets(exptex2Parser.Atom_bracketsContext ctx);
	void enterEntity_sf_id(exptex2Parser.Entity_sf_idContext ctx);
	void exitEntity_sf_id(exptex2Parser.Entity_sf_idContext ctx);
	void enterSum(exptex2Parser.SumContext ctx);
	void exitSum(exptex2Parser.SumContext ctx);
	void enterExpr_negate(exptex2Parser.Expr_negateContext ctx);
	void exitExpr_negate(exptex2Parser.Expr_negateContext ctx);
	void enterEntity_id(exptex2Parser.Entity_idContext ctx);
	void exitEntity_id(exptex2Parser.Entity_idContext ctx);
	void enterEntity_num(exptex2Parser.Entity_numContext ctx);
	void exitEntity_num(exptex2Parser.Entity_numContext ctx);
	void enterEntity_string(exptex2Parser.Entity_stringContext ctx);
	void exitEntity_string(exptex2Parser.Entity_stringContext ctx);
	void enterMinus_expr_minus(exptex2Parser.Minus_expr_minusContext ctx);
	void exitMinus_expr_minus(exptex2Parser.Minus_expr_minusContext ctx);
	void enterMinus_expr_normal(exptex2Parser.Minus_expr_normalContext ctx);
	void exitMinus_expr_normal(exptex2Parser.Minus_expr_normalContext ctx);
	void enterExpr_comprehend(exptex2Parser.Expr_comprehendContext ctx);
	void exitExpr_comprehend(exptex2Parser.Expr_comprehendContext ctx);
	void enterProb(exptex2Parser.ProbContext ctx);
	void exitProb(exptex2Parser.ProbContext ctx);
	void enterChoose(exptex2Parser.ChooseContext ctx);
	void exitChoose(exptex2Parser.ChooseContext ctx);
	void enterMath_symbol(exptex2Parser.Math_symbolContext ctx);
	void exitMath_symbol(exptex2Parser.Math_symbolContext ctx);
	void enterProd(exptex2Parser.ProdContext ctx);
	void exitProd(exptex2Parser.ProdContext ctx);
	void enterAtom_entity(exptex2Parser.Atom_entityContext ctx);
	void exitAtom_entity(exptex2Parser.Atom_entityContext ctx);
	void enterLim(exptex2Parser.LimContext ctx);
	void exitLim(exptex2Parser.LimContext ctx);
	void enterAlign(exptex2Parser.AlignContext ctx);
	void exitAlign(exptex2Parser.AlignContext ctx);
	void enterAtom_choose(exptex2Parser.Atom_chooseContext ctx);
	void exitAtom_choose(exptex2Parser.Atom_chooseContext ctx);
	void enterEntity_bb_id(exptex2Parser.Entity_bb_idContext ctx);
	void exitEntity_bb_id(exptex2Parser.Entity_bb_idContext ctx);
	void enterExpr_impl_mult(exptex2Parser.Expr_impl_multContext ctx);
	void exitExpr_impl_mult(exptex2Parser.Expr_impl_multContext ctx);
	void enterStuff(exptex2Parser.StuffContext ctx);
	void exitStuff(exptex2Parser.StuffContext ctx);
	void enterStart(exptex2Parser.StartContext ctx);
	void exitStart(exptex2Parser.StartContext ctx);
	void enterExpr_func(exptex2Parser.Expr_funcContext ctx);
	void exitExpr_func(exptex2Parser.Expr_funcContext ctx);
	void enterExpr_atom(exptex2Parser.Expr_atomContext ctx);
	void exitExpr_atom(exptex2Parser.Expr_atomContext ctx);
	void enterComprehension(exptex2Parser.ComprehensionContext ctx);
	void exitComprehension(exptex2Parser.ComprehensionContext ctx);
}